package org.example.Student;

import org.example.Course.Course;

import java.util.ArrayList;
import java.util.UUID;

public class Student {
    String id;
    String firstName;
    String lastName;
    int age;
    double balance;
    ArrayList<UUID> courses = new ArrayList<>();

    public Student(String firstName, String lastName, int age, double balance) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
        this.balance = balance;

        // This is the beginning implementation
        // This will be more random and generated by the database
        this.id = UUID.randomUUID().toString();
    }

    public Student(String firstName, String lastName, int age, double balance, UUID courseID) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
        this.balance = balance;
        this.courses.add(courseID);

        // This is the beginning implementation
        // This will be more random and generated by the database
        this.id = UUID.randomUUID().toString();
    }

    public Student(String firstName, String lastName, int age, double balance, ArrayList<UUID> coursesID) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
        this.balance = balance;
        this.courses = coursesID;

        // This is the beginning implementation
        // This will be more random and generated by the database
        this.id = UUID.randomUUID().toString();
    }

    public Student() {}

    public String getId() {
        return id;
    }

    public void setId(String id) {this.id = id;}

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public double getBalance() {
        return balance;
    }

    public void setBalance(double balance) {
        this.balance = balance;
    }

    public String addStudentToCourse(UUID courseID){
        courses.add(courseID);

        return "Successfully added: " + courseID;
    }

    public String addStudentToCourse(ArrayList<UUID> courseIDs){
        courses = courseIDs;

        return "Successfully added: " + courseIDs;
    }

    public ArrayList<UUID> getCourses() {
        return courses;
    }

    public String removeCourse(UUID courseID){
        courses.remove(courseID);

        return "Successfully remove: " + courseID;
    }

    public void setCourses(ArrayList<UUID> courseIDs) {
        courses = courseIDs;
    }


    @Override
    public String toString() {
        return "Student{" +
                "uuid='" + id + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", age=" + age +
                ", balance=" + balance +
                ", courses=" + courses +
                '}';
    }

}
